### ISSUE TITLE
cannot connect

### ISSUE THREAD

**Issue by jhallam3** [haseebmukhtar/AdobeSign.Net#3]
Hi, using this code below 

  var ApiURL = "https://api.eu1.echosign.com/api/rest/v5/";
    var accessToken = "my token";

    AdobeSignNet.RestAPI api = new AdobeSignNet.RestAPI(ApiURL, accessToken);
    AdobeSignNet.AdobeObject obj = new AdobeSignNet.AdobeObject(api);
    var agreements = await obj.GetAgreements();

Visual Studio just stops on the await. 

Am I missing something?

**Comment by haseebmukhtar** [comment]
Hi

Your code seems to be fine. I have just tested with same code and it is working.
I think it's async issue, is you method defined properly for async / await.

My test code is:
```
private async Task ShowAgreements()
        {
            string apiURL = txtApiURL.Text;
            string accessToken = txtAccessToken.Text;

            AdobeSignNet.RestAPI api = new AdobeSignNet.RestAPI(apiURL, accessToken);
            AdobeSignNet.AdobeObject obj = new AdobeSignNet.AdobeObject(api);

            var agreements = await obj.GetAgreements();           

            foreach (var agreement in agreements.userAgreementList)
            {
                listBox1.Items.Add(agreement);
            }
        }
```

Can you please give us complete method code.

Thanks

**Comment by jhallam3** [comment]
Hi, thanks for getting back to me. 

I’ve got a .net class thats I’m going which has references to your code. 

I’ve taken your SendDocument code and added that to my class and then calling that from a program. 

I’ve made a video here > https://www.screencast.com/t/4Oxr9rEt to show whats happening. 

Thanks in advance

**Comment by haseebmukhtar** [comment]
Hi,
Can not run the video. If possible can you please explain here.

Thanks

**Comment by jhallam3** [comment]
Hi, 

So when I get to an await in the code the application just stops. Thats whats confusing.

**Comment by haseebmukhtar** [comment]
Hi,

Can you send your project.

Thanks

**Comment by jhallam3** [comment]
Hi, 

https://drive.google.com/a/decisions.com/file/d/0Bw5zomFrY_M6aVNITjJVM3dDeWM/view?usp=sharing

See link above. 

Thanks for taking time to help me

**Comment by haseebmukhtar** [comment]
Hi
You need to wait for async method call from console application.

Change this line
`var checkConnectivity = new Esign.EsignAPI().SendDocument("https://api.na2.echosign.com/api/rest/v5/", "3AAABLH**********************qOQhPQDNp2JWi", @"C:\Temp\TEST DOC.docx", "Test", "Jon.hallam@managed-desktop.com");`

to 
`
new Esign.EsignAPI().SendDocument("https://api.na2.echosign.com/api/rest/v5/", "3AAABLm*******************s1gQKqOQhPQDNp2JWi", @"C:\Temp\TEST DOC.docx", "Test", "Jon.hallam@managed-desktop.com").Wait();`

in static void Main(string[] args) method of your project.

Thanks

**Comment by haseebmukhtar** [comment]
Hi jhallam3,

Is this issue is resolved.

**Comment by jhallam3** [comment]
Yes thanks for all your efforts!

Great connector!

Works really well!

Regards

Jon Hallam


On 6 Sep 2017, at 12:19, haseebmukhtar <notifications@github.com> wrote:

Hi jhallam3,

Is this issue is resolved.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/haseebmukhtar/AdobeSign.Net/issues/3#issuecomment-327453384>,
or mute the thread
